//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deathworlders.MarkdownConvert.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkdownConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Cover&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;style.css&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @page {
        ///            padding: 0;
        ///            margin: 0;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;img src=&quot;{cover}&quot; alt=&quot;Girl in a jacket&quot;&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string epub_cover_template {
            get {
                return ResourceManager.GetString("epub_cover_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{title}&lt;/title&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;style.css&quot; /&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    @page {
        ///      padding: 0;
        ///      margin: 0;
        ///    }
        ///  &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  {body}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string epub_template {
            get {
                return ResourceManager.GetString("epub_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;{title}&lt;/title&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    {style}
        ///  &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  {body}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string pdf_template {
            get {
                return ResourceManager.GetString("pdf_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pagebreak {
        ///    page-break-before: always;
        ///}
        ///body {
        ///    margin: 0;
        ///    padding: 0;
        ///    overflow-x: hidden;
        ///    color: #333
        ///}
        ///*, html {
        ///    letter-spacing: 0.1px;
        ///    font-size: 5mm;
        ///    font-family: &quot;Roboto Slab&quot;, serif;
        ///}
        ///
        ///h1, h2, h3, h4, h5, h6, time {
        ///    font-family: &quot;Ruda&quot;,sans-serif
        ///}
        ///
        ///.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
